apiVersion: apps/v1
kind: Deployment
metadata:
        name: node-app
        labels:
                app: node-app
        spec:
                replicas: 3
                selector:
                        matchLabels:
                                app: node-app
                        template:
                                metedata:
                                        labels:
                                                app: node-app
                                                tier: node-app
                                spec:
                                        containers:
                                                - name: node-app
                                                  image: jisoohwang/rego:latest
                                                  imagePullPolicy: Always
                                                  ports: 
                                                - containterPort: 3000
                                                  name: node-app
---
apiVersion: v1
kind: Service
metadata:
        name: node-app
        labels:
                app: node-app
spec:
        ports:
                - port: 80
                  targetPort: 3000
        selector:
                app: node-app
                tier: node-app
        type: LoadBalancer
