apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
   - port: 3306
    clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-state
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  serviceName: mysql-service
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0.28
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_HOST
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: host
          - name: MYSQL_PORT
            valueFrom:
              configMapKeyRef: 
                name: mysql-config
                key: port
          - name: MYSQL_DATABASE
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: database
          - name: MYSQL_USER
            valueFrom:
              configMapKeyRef:
                name: mysql-config
                key: user
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: root_password
          - name: MYSQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-secret
                key: password
        volumeMounts:
        - name: mysql-config
          mountPath: "/config"
          readOnly: true
        - name: mysql-ps
          mountPath: /var/lib/mysql
          subPath: mysql
        readinessProbe:
          exec:
            command:
            - bash
            - "-c"
            - |
              mysql -h127.0.0.1 -uroot -p$MYSQL_ROOT_PASSWORD -e'SELECT 1'
          initialDelaySeconds: 5
          periodSeconds: 2
          timeoutSeconds: 1
        livenessProbe:
          exec:
            command:
            - bash
            - "-c"
            - |
              mysqladmin -uroot -p$MYSQL_ROOT_PASSWORD ping
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
      volumes:
        - name: mysql-config
          configMap:
            name: mysql-config
            items:
              - key: "host"
                path: "host"
              - key: "port"
                path: "port"
              - key: "database"
                path: "database" 
              - key: "user"
                path: "user"
        - name: mysql-ps
          persistentVolumeClaim:
            claimName: mysql-pv-claim
